/**
 * Conversation management utilities
 */

import { Conversation, Message, ConversationMetadata, ConversationFilter, ConversationSortOptions } from '../types/conversation';

/**
 * Generate an automatic title from the first user message
 */
export function generateConversationTitle(firstMessage: string): string {
  if (!firstMessage || firstMessage.trim().length === 0) {
    return 'New Chat';
  }

  // Clean the message content
  const cleaned = firstMessage.trim();
  
  // If message is very short, use it as-is
  if (cleaned.length <= 30) {
    return cleaned;
  }

  // Try to extract a meaningful title
  const sentences = cleaned.split(/[.!?]+/);
  const firstSentence = sentences[0]?.trim();
  
  if (firstSentence && firstSentence.length <= 50) {
    return firstSentence;
  }

  // Extract key phrases or questions
  const questionMatch = cleaned.match(/^(what|how|why|when|where|who|which|can|could|would|should|is|are|do|does|did)[^.!?]*[?]?/i);
  if (questionMatch && questionMatch[0].length <= 60) {
    return questionMatch[0].replace(/[?]*$/, '');
  }

  // Look for imperative statements
  const imperativeMatch = cleaned.match(/^(help|explain|tell|show|create|make|write|generate|find|search)[^.!?]*/i);
  if (imperativeMatch && imperativeMatch[0].length <= 60) {
    return imperativeMatch[0];
  }

  // Fall back to truncating at word boundaries
  const words = cleaned.split(' ');
  let title = '';
  
  for (const word of words) {
    if ((title + ' ' + word).length > 50) {
      break;
    }
    title += (title ? ' ' : '') + word;
  }

  return title || 'New Chat';
}

/**
 * Create initial conversation metadata
 */
export function createConversationMetadata(): ConversationMetadata {
  const now = new Date();
  return {
    createdAt: now,
    updatedAt: now,
    messageCount: 0,
    tokenCount: 0,
    tags: [],
    isArchived: false,
    isFavorite: false,
    autoTitleGenerated: false,
    lastActivity: now,
    totalCost: 0
  };
}

/**
 * Update conversation metadata when messages change
 */
export function updateConversationMetadata(
  conversation: Conversation,
  messages: Message[]
): ConversationMetadata {
  const now = new Date();
  const tokenCount = messages.reduce((sum, msg) => sum + (msg.tokens || 0), 0);
  
  return {
    ...conversation.metadata,
    updatedAt: now,
    messageCount: messages.length,
    tokenCount,
    lastActivity: now
  };
}

/**
 * Create a new conversation with proper initialization
 */
export function createNewConversation(id?: string): Conversation {
  const conversationId = id || Date.now().toString();
  const now = new Date();
  
  return {
    id: conversationId,
    title: 'New Chat',
    messages: [],
    lastMessage: now,
    metadata: createConversationMetadata()
  };
}

/**
 * Update conversation title and metadata
 */
export function updateConversationTitle(
  conversation: Conversation,
  newTitle: string,
  autoGenerated: boolean = false
): Conversation {
  return {
    ...conversation,
    title: newTitle.trim(),
    metadata: {
      ...conversation.metadata,
      updatedAt: new Date(),
      autoTitleGenerated: autoGenerated
    }
  };
}

/**
 * Add a message to conversation and update metadata
 */
export function addMessageToConversation(
  conversation: Conversation,
  message: Message
): Conversation {
  const newMessages = [...conversation.messages, message];
  let updatedTitle = conversation.title;
  let autoTitleGenerated = conversation.metadata.autoTitleGenerated;

  // Auto-generate title from first user message if title is still default
  if (
    message.role === 'user' && 
    conversation.messages.length === 0 && 
    (conversation.title === 'New Chat' || !conversation.metadata.autoTitleGenerated)
  ) {
    updatedTitle = generateConversationTitle(message.content);
    autoTitleGenerated = true;
  }

  return {
    ...conversation,
    title: updatedTitle,
    messages: newMessages,
    lastMessage: message.timestamp,
    metadata: {
      ...updateConversationMetadata(conversation, newMessages),
      autoTitleGenerated
    }
  };
}

/**
 * Filter conversations based on criteria
 */
export function filterConversations(
  conversations: Conversation[],
  filter: ConversationFilter
): Conversation[] {
  return conversations.filter(conversation => {
    // Text search in title and messages
    if (filter.query) {
      const query = filter.query.toLowerCase();
      const titleMatch = conversation.title.toLowerCase().includes(query);
      const messageMatch = conversation.messages.some(msg => 
        msg.content.toLowerCase().includes(query)
      );
      if (!titleMatch && !messageMatch) {
        return false;
      }
    }

    // Tag filter
    if (filter.tags && filter.tags.length > 0) {
      const hasMatchingTag = filter.tags.some(tag => 
        conversation.metadata.tags.includes(tag)
      );
      if (!hasMatchingTag) {
        return false;
      }
    }

    // Date range filter
    if (filter.dateRange) {
      const conversationDate = conversation.metadata.createdAt;
      if (conversationDate < filter.dateRange.start || conversationDate > filter.dateRange.end) {
        return false;
      }
    }

    // Model filter
    if (filter.model && conversation.metadata.model !== filter.model) {
      return false;
    }

    // Archive filter
    if (filter.isArchived !== undefined && conversation.metadata.isArchived !== filter.isArchived) {
      return false;
    }

    // Favorite filter
    if (filter.isFavorite !== undefined && conversation.metadata.isFavorite !== filter.isFavorite) {
      return false;
    }

    return true;
  });
}

/**
 * Sort conversations based on options
 */
export function sortConversations(
  conversations: Conversation[],
  sortOptions: ConversationSortOptions
): Conversation[] {
  return [...conversations].sort((a, b) => {
    let aValue: any;
    let bValue: any;

    switch (sortOptions.field) {
      case 'title':
        aValue = a.title.toLowerCase();
        bValue = b.title.toLowerCase();
        break;
      case 'lastMessage':
        aValue = a.lastMessage.getTime();
        bValue = b.lastMessage.getTime();
        break;
      case 'createdAt':
        aValue = a.metadata.createdAt.getTime();
        bValue = b.metadata.createdAt.getTime();
        break;
      case 'messageCount':
        aValue = a.metadata.messageCount;
        bValue = b.metadata.messageCount;
        break;
      case 'tokenCount':
        aValue = a.metadata.tokenCount;
        bValue = b.metadata.tokenCount;
        break;
      default:
        aValue = a.lastMessage.getTime();
        bValue = b.lastMessage.getTime();
    }

    let comparison = 0;
    if (aValue < bValue) {
      comparison = -1;
    } else if (aValue > bValue) {
      comparison = 1;
    }

    return sortOptions.direction === 'desc' ? -comparison : comparison;
  });
}

/**
 * Export conversation to various formats
 */
export function exportConversation(conversation: Conversation, format: 'txt' | 'json' | 'md' = 'txt'): string {
  switch (format) {
    case 'json':
      return JSON.stringify(conversation, null, 2);
    
    case 'md':
      let markdown = `# ${conversation.title}\n\n`;
      markdown += `**Created:** ${conversation.metadata.createdAt.toLocaleString()}\n`;
      markdown += `**Messages:** ${conversation.metadata.messageCount}\n`;
      if (conversation.metadata.tokenCount > 0) {
        markdown += `**Tokens:** ${conversation.metadata.tokenCount}\n`;
      }
      markdown += '\n---\n\n';
      
      conversation.messages.forEach(message => {
        const role = message.role.charAt(0).toUpperCase() + message.role.slice(1);
        markdown += `## ${role}\n\n${message.content}\n\n`;
        if (message.timestamp) {
          markdown += `*${message.timestamp.toLocaleString()}*\n\n`;
        }
      });
      
      return markdown;
    
    case 'txt':
    default:
      let text = `${conversation.title}\n`;
      text += `Created: ${conversation.metadata.createdAt.toLocaleString()}\n`;
      text += `Messages: ${conversation.metadata.messageCount}\n`;
      if (conversation.metadata.tokenCount > 0) {
        text += `Tokens: ${conversation.metadata.tokenCount}\n`;
      }
      text += '\n' + '='.repeat(50) + '\n\n';
      
      conversation.messages.forEach(message => {
        text += `${message.role.toUpperCase()}: ${message.content}\n\n`;
      });
      
      return text;
  }
}

/**
 * Validate conversation data
 */
export function validateConversation(conversation: any): conversation is Conversation {
  return (
    conversation &&
    typeof conversation.id === 'string' &&
    typeof conversation.title === 'string' &&
    Array.isArray(conversation.messages) &&
    conversation.lastMessage instanceof Date &&
    conversation.metadata &&
    typeof conversation.metadata === 'object'
  );
}

/**
 * Migrate old conversation format to new format
 */
export function migrateConversation(oldConversation: any): Conversation {
  // Handle old format without metadata
  if (!oldConversation.metadata) {
    const now = new Date();
    return {
      id: oldConversation.id || Date.now().toString(),
      title: oldConversation.title || 'Migrated Chat',
      messages: oldConversation.messages || [],
      lastMessage: oldConversation.lastMessage || now,
      metadata: {
        createdAt: oldConversation.createdAt || now,
        updatedAt: now,
        messageCount: oldConversation.messages?.length || 0,
        tokenCount: 0,
        tags: [],
        isArchived: false,
        isFavorite: false,
        autoTitleGenerated: false,
        lastActivity: oldConversation.lastMessage || now,
        totalCost: 0
      }
    };
  }

  return oldConversation as Conversation;
}